import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useState } from "react";
import { Header } from "~/components/Header";
import { api, type RouterOutputs } from "../utils/api";
import NoteEditor from "~/components/NoteEditor";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Notetaker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      
      <main>
        <Header />
        <Content />
      </main>
    </>
  );
};

export default Home;

type Topic = RouterOutputs['topic']['getAll'][0];

const Content: React.FC = () => {
  const {data: sessionData } = useSession();

  const [selectedTopic, setSelectecTopic] = useState<Topic | null>(null);

  // eslint-disabled-next-line
  const { data: topics, refetch: refecthTopics } = api.topic.getAll.useQuery(
    undefined,
    {
      enabled: sessionData?.user !== undefined,
      onSuccess: (data) => {
        setSelectecTopic(selectedTopic ?? data[0] ?? null);
      }
    }
  );

  const createTopic = api.topic.create.useMutation({
    onSuccess: () => {
      void refecthTopics();
    }
  });

  return (
    <div className="mx-5 mt-5 grid grid-cols-4 gap-2">
      <div className="px-2">
        <ul className="menu rounded-box w-56 bg-base-100 p-2">
          {topics?.map((topic) => (
            <li key={topic.id}>
              <a href="#"
                onClick={(e) => {
                  e.preventDefault();
                  setSelectecTopic(topic);
                }}>
                {topic.title}
              </a>
            </li>
          ))}
        </ul>
        <div className="divider"></div>
        <input 
          type="text"
          placeholder="New topic"
          className="input-bordered input input-sm w-full"
          onKeyDown={(e) => {
            if (e.key === 'Enter') {
              createTopic.mutate({
                title: e.currentTarget.value,
              });
              e.currentTarget.value = '';
            }
          }}
        />

      </div>
      <div className="col-span-3">
        <NoteEditor />
      </div>

    </div>
  )
}
